---

version: "3"

services:
  nginx:
    depends_on:
      - nextcloud
      - mattermost
      - confluence
      - jira
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  jira:
    depends_on:
      - postgres
    image: cptactionhank/atlassian-jira-software:${JIRA_VERSION}
    restart: always
    networks:
      - nginx
      - postgres
    volumes:
      - jira:/var/atlassian/jira
    environment:
      - CATALINA_CONNECTOR_PROXYNAME=${JIRA_CATALINA_CONNECTOR_PROXYNAME}
      - CATALINA_CONNECTOR_PROXYPORT=${JIRA_CATALINA_CONNECTOR_PROXYPORT}
      - CATALINA_CONNECTOR_SCHEME=${JIRA_CATALINA_CONNECTOR_SCHEME}
      - CATALINA_CONNECTOR_SECURE=${JIRA_CATALINA_CONNECTOR_SECURE}

  confluence:
    depends_on:
      - postgres
    image: atlassian/confluence-server:${CONFLUENCE_VERSION}
    restart: always
    networks:
      - nginx
      - postgres
    volumes:
      - confluence:/var/atlassian/application-data/confluence
    environment:
      - CATALINA_CONNECTOR_PROXYNAME=${CONFLUENCE_CATALINA_CONNECTOR_PROXYNAME}
      - CATALINA_CONNECTOR_PROXYPORT=${CONFLUENCE_CATALINA_CONNECTOR_PROXYPORT}
      - CATALINA_CONNECTOR_SCHEME=${CONFLUENCE_CATALINA_CONNECTOR_SCHEME}
      - CATALINA_CONNECTOR_SECURE=${CONFLUENCE_CATALINA_CONNECTOR_SECURE}

  mattermost:
    depends_on:
      - postgres
    image: mattermost/platform:${MATTERMOST_VERSION}
    restart: always
    networks:
      - nginx
      - postgres
    volumes:
      - mattermost_data:/mattermost-data
      - mattermost_sql:/var/lib/mysql

  nextcloud:
    depends_on:
      - postgres
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    networks:
      - nginx
      - postgres
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_USER}

networks:
  nginx:
  postgres:

volumes:
  postgres:
  nextcloud:
  confluence:
  jira:
  mattermost_data:
  mattermost_sql:
